# Generated by Django 5.2.2 on 2025-06-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, default='img/noimage.jpg', upload_to='img/'),
        ),
    ]
