# Generated by Django 5.2.2 on 2025-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_comment_slug_comment_post'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
